services:
  - type: web
    name: ktc-dashboard
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: SHEET_ID
        value: "16nhZJyAiCX7xzBujieAF1AOas6bgh2-4X6ePQixWHJE"
      - key: SHEET_GID
        value: "0"
    autoDeploy: true
    plan: free
